### ISSUE TITLE
Limiting the time when the PV excess automation is in effect

### ISSUE THREAD

**Issue by jko75** [InventoCasa/ha-advanced-blueprints#12]
It would be convenient to be able to set the time of day when the PV excess automation is enabled, and when it's disabled.

TLDR:
Hi, I have been testing this for a few days/nights. My system does not have a battery, and I need to run the appliances (heating, car charging) also during the night when I have no excess PV power. My other timers and file_pv_excess_control_on_time ended up switching stuff on and off competitively during the night because the PV power is zero. I tried fixing it by adding manually to the automations a time condition, but adding that condition stopped the repetitive running of file_pv_excess_control_on_time.

**Comment by InventoCasa** [comment]
Hi there,

this is actually already possible very easily:
You can set up a simple automation which switches the PV excess automations on or off depending on the time. When the PV excess automation of a specific appliance gets disabled, it will be excluded from the PV excess optimization.
