### ISSUE TITLE
Automation is triggering my appliance on multiple times per day

### ISSUE THREAD

**Issue by finalbillybong** [InventoCasa/ha-advanced-blueprints#22]
As title - My washing machine as been turned on 5 times today now so I have disabled the automation for now. Is it possible to restrict the automation to only trigger once in a 24 hour period?

**Comment by InventoCasa** [comment]
See my answer in the HA community forum.

>  I guess I could include a simple “only run appliance once” switch. Till I implemented this, you could help yourself with two simple automations:
> - one, which triggers when the washing machine gets turned on and disables the PV excess automation for the washing machine
> - another one, which enables the PV excess automation for the washing machine again at midnight

**Comment by finalbillybong** [comment]
That’s a great suggestion. Can’t believe I didn’t think of that. Thanks
