### ISSUE TITLE
Failed to load blueprint: mapping values are not allowed here in "/config/blueprints/automation/PV_Excess_Contol/pv_excess_control.yaml", line 28, column 66

### ISSUE THREAD

**Issue by rolf1982** [InventoCasa/ha-advanced-blueprints#29]
Hello everyone, I mean I have installed everything correctly.
Unfortunately I get the following error message in the listing of the blueprints: Failed to load blueprint: mapping values are not allowed here in "/config/blueprints/automation/PV_Excess_Contol/pv_excess_control.yaml", line 28, column 66

Can someone help me here?

VG
Rolf

**Comment by InventoCasa** [comment]
Hello Rolf, 

normally line 28 of the YAML file is completely empty. 
It's likely that you made an error while copying files, resulting in line 28 being not empty, and some code being indented incorrectly. 

Did you install everything according to instructions provided? 
Did you copy the files as-is, or did you copy&paste their content?

**Comment by rolf1982** [comment]
Hello Hendrik, I have found the error.
Whenever I right clicked the "save link as" it downloaded me the "pv_excess_control.yaml" file, but there is a web page content in there and not what was displayed in the code field on the web page.
I have now manually overwritten the content and it works.

Thanks for the quick support.

Many greetings
Rolf
