### ISSUE TITLE
Failed to load blueprint: mapping values are not allowed here in "/config/blueprints/automation/pv_excess_control.yaml", line 195, column 74

### ISSUE THREAD

**Issue by jobvanes** [InventoCasa/ha-advanced-blueprints#31]
Dear,

I'm running 2023.6.1 and receiving errors now on the blueprint.
Failed to load blueprint: mapping values are not allowed here in "/config/blueprints/automation/pv_excess_control.yaml", line 195, column 74

**Comment by InventoCasa** [comment]
Just tested with newest pyscript (1.5.0) + HA version (2023.11.1). No problems here.
I suggest updating to the latest HA + pyscript version, and (if that didn't help) a reinstallation of pyscript and the PV excess control script.
