### ISSUE TITLE
domain: sensor error in yaml

### ISSUE THREAD

**Issue by coolnetworks** [InventoCasa/ha-advanced-blueprints#37]
![image](https://github.com/InventoCasa/ha-advanced-blueprints/assets/21252210/3fe0e00f-484f-4af7-af1c-12006fffefb4)

**Comment by corautem** [comment]
I have the same errors, Although the automation is working just fine it's a bit annoying as every time I open the Studio Code Server the warning pops out.

**Comment by ChunkyMonkey** [comment]
Does any one know why this error is happening in VS Code?

**Comment by InventoCasa** [comment]
This has nothing to do with the script or Home Assistant, so I do not see a reason to look further into this
