### ISSUE TITLE
EVSE charger control ON/OFF

### ISSUE THREAD

**Issue by nrp929** [InventoCasa/ha-advanced-blueprints#41]
I keep getting this error with my Wallbox Pulsar Plus. It's on version 5.17.50. This error shows up with both the OCPP integration and the wallbox integration. Since it's assuming OFF state, the automation doesn't turn off the EVSE when the solar panels aren't producing enough kW. Maybe it just needs to wait a little longer to get a response? Is it possible to introduce a delay timer when checking on Appliance state? Thanks. 

```
This error originated from a custom integration.

Logger: custom_components.pyscript.file.pv_excess_control.on_time
Source: custom_components/pyscript/eval.py:1911
Integration: Pyscript Python scripting (documentation, issues)
First occurred: 7:16:19 AM (2 occurrences)
Last logged: 7:16:19 AM

[switch.charger_charge_control (Prio 1)] Appliance state (=unavailable) is neither ON nor OFF. Assuming OFF state.
```

**Comment by InventoCasa** [comment]
Hi, something must be wrong with the state of your switch entity which you pass to the script. The entity state is only unavailable if there are connection issues between your appliance and Home Assistant.
Check your switch entity history bar in Home Assistant to confirm this.
