### ISSUE TITLE
Failed to load blueprint: while parsing a block mapping

### ISSUE THREAD

**Issue by 2senel** [InventoCasa/ha-advanced-blueprints#71]
Hi,

I have used the latest version of pv_excess_control.yaml and it can't be loaded due to parsing error:

![image](https://github.com/InventoCasa/ha-advanced-blueprints/assets/5936814/7b9d02d8-ae25-4a2a-9c28-d5ee07ba5420)
![image](https://github.com/InventoCasa/ha-advanced-blueprints/assets/5936814/6b98eb25-3c06-40ed-b89f-2e4c0ebd73bc)

**Comment by InventoCasa** [comment]
You're right, seems like I overlooked a missing ". Will fix it right now

**Comment by InventoCasa** [comment]
Fixed

**Comment by Maik7** [comment]
I think I caused that. Sorry for that.
