### ISSUE TITLE
EV charger treated as if drawing power even when it is not?

### ISSUE THREAD

**Issue by ThorAlex87** [InventoCasa/ha-advanced-blueprints#75]
I had a Amina S EV charger installed a while ago, so I have been experimenting with automations for it, but I'm having issues with the script here. I do not have an EV yet so I have not tested with an actual load, but my parents will be visisting with a plugin hybrid later this summer so I hope to have it ready for testing then.

The issue is the script seems to treat the charger as if it's always drawing the minimum 6A whenever it's on, even thought the sensor reading is 0W and there is no EV connected. This means lower priority devices will not be turned on on cloudy days, even with plenty of excess. 

I updated to the newest version today and the problem is still there. Not sure if there is an issue with the script or with my setup, but I've looked over the blueprint many times and cannot find any errors.

Maybe adding an optional check for an "EV connected" sensor and ignore the charger if it's not connected could be an upgrade? No point in trying to control a device that cannot draw any power, thought I'm not sure if there is any actual benefit in that other than as a workaround for my problem...

(For now I can just deactivate the blueprint for the charger, and since I don't have an EV this is not a high priority issue yet.)

**Comment by Maik7** [comment]
can you post some logs? This should help to analyse the issue. Ideally change the log level to debug.

**Comment by ThorAlex87** [comment]
Closed, as it's probably me misreading the data or a weird one time occurrence.
